# Generated by Django 3.1.1 on 2020-12-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('u_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('particulars', models.CharField(max_length=1000)),
                ('qty', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('paid', models.CharField(max_length=100)),
                ('remaining', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('name_of_reciver', models.CharField(max_length=500)),
                ('particulars', models.CharField(max_length=500)),
                ('qty', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('u_id', models.CharField(max_length=100)),
                ('issue_by', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('u_id', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=1000)),
                ('qty', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
